index:
    path: /
    controller: App\Controller\DefaultController::index

car_th_get:
    path: /car/th/get/{id}
    controller: App\Controller\CarTHController::getById
    defaults:
        id: 1
    requirements:
        id: '\d+'